apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-nien
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-nien
    app.kubernetes.io/part-of: tkrw-pr714-0075-0041-app
  name: devfile-sample-nien
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-nien
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-nien
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0041-tenant/tkrw-pr714-0075-0041-app/devfile-sample-nien@sha256:576b158205dbba050e03c65727cce0c82cd02be6fa064c8cfa844d77e586bc9c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
